# See https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema

trigger:
  - master

jobs:
- job: Linux
  timeoutInMinutes: 20
  pool:
    vmImage: 'ubuntu-20.04'
  variables:
    CI_OS: linux
  steps:
    - template: .azure-pipelines/posix.yml
  strategy:
    matrix:
      latest:
        DMD_VERSION: 2.100.0
        DOCKERFILE: Dockerfile
      # min:
      #   DMD_VERSION: 2.087.1
      #   DOCKERFILE: Dockerfile
